#3 - последняя версия            
version: '3'
#контейнеры
services:
#web - мое приложение без бд
    web:
        build: .
        image: super_duper_url_web
        ports:
            - "5000:5000"
        #команда по умолчанию
        command: gunicorn -b :5000 --access-logfile - --error-logfile - main:app
        #в каталоге файл .env содержит единственную строчку FLASK APP=main.py
        volumes:
            - ./:/home/app
        #env_file: .flaskenv
        enviroment:
            FLASK_APP: "main.py"
    #бд    
    db:
        image: postgres:latest
        container_name: super_duper_url_db
